### ISSUE TITLE
Please List ELTCOIN

### ISSUE THREAD

**Issue by Steake** [bonnag/ubitok.io#3]
# ELTCOIN

We donated 75k ELTCOIN to you at the ETH address `0x884378D7919125BDfd337145d871a1bA2a58c0E9`

We also sent you some ETH for gas at the same address, tx hash is `0x29e3af9711e880b4d08cacfdb9f4e2de9cc645e871b4af42bd70d1e4cc286be0`

## Token Info

Contract Address: 0x44197a4c44d6a059297caf6be4f7e172bd56caaf

- Token name ELTCOIN
- Token ticker code ELTCOIN or ELT
- Decimal positions 8
- Square logo of at least 100 x 100 px https://i.imgur.com/hkoUjf4.png
- Link to verified contract on etherscan.io https://etherscan.io/address/0x44197a4c44d6a059297caf6be4f7e172bd56caaf#code

Regards
Oli

**Comment by kieranelby** [comment]
Great, thanks for the generous donation to cover our gas costs!

I've added ELTCOIN to the "Coming Soon" list at https://ubitok.io/products/.

I've also created the UbiTok.io book smart contract for it.

Unfortunately, I've realised that our UbiTok.io front-end doesn't currently handle low-valued tokens very well - I notice ELTCOIN is trading around 1 ELTCOIN = 0.000007 ETH, which is only a little bit above the smallest price supported on UbiTok.io. I don't want to list it today only to find the price goes down and it can't be traded :(

Don't worry though, we (UbiTok.io) will do some development work to support smaller prices for tokens like ELTCOIN - it's not difficult, just a bit fiddly - we will list ELTCOIN later this week. Hope that's OK!

**Comment by kieranelby** [comment]
Right, ELTCOIN is now listed on UbiTok.io, link is: https://ubitok.io/exchange/?pairId=ELTCOIN-ETH .

**Comment by kieranelby** [comment]
By the way, when you said you donated 75k ELTCOIN to us at 0x884378D7919125BDfd337145d871a1bA2a58c0E9, I think you accidentally donated 750k ELTCOIN - that seems too much! Shall I send the extra 675k (750k-75k) ELTCOIN back to 0xdcBd3b5605A525f12819958E0Cb02941C539EAb6 ?

**Comment by Steake** [comment]
Oops!

Please do send back 600k, keep the extra as a thank you for your honesty!

Many thanks for listing ELTCOIN in such a short period of time :)

**Comment by kieranelby** [comment]
No problem, have sent 600k back now ( tx is https://etherscan.io/tx/0x2113730c184c4d0b04c42f65f6c14b7da8c91e20a309c7db6a5d974c9f3c94c2 ) :)
